### ISSUE TITLE
/overview is erroring

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#550]
`/overview` is throwing a 500 error, at least for my user account, and shows the following stack dump in the `production.log`:

```
I, [2016-03-26T22:43:20.236002 #2349]  INFO -- : Started GET "/overview" for 82.2.125.53 at 2016-03-26 22:43:20 +0000
I, [2016-03-26T22:43:20.240328 #2349]  INFO -- : Processing by DashboardsController#show as HTML
I, [2016-03-26T22:43:20.472475 #2349]  INFO -- :   Rendered dashboards/show.html.haml within layouts/application (200.2ms)
I, [2016-03-26T22:43:20.472767 #2349]  INFO -- : Completed 500 Internal Server Error in 232ms (ActiveRecord: 42.3ms)
I, [2016-03-26T22:43:20.483480 #2349]  INFO -- : [Rollbar] Scheduling payload
I, [2016-03-26T22:43:20.483610 #2349]  INFO -- : [Rollbar] Sending payload
I, [2016-03-26T22:43:21.200025 #2349]  INFO -- : [Rollbar] Success
I, [2016-03-26T22:43:21.200444 #2349]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=e4482e8d-73db-43fc-87a7-cd6b5b9940f3 (only available if report was successful)
F, [2016-03-26T22:43:21.205524 #2349] FATAL -- :
ActionView::Template::Error (undefined method `component_name' for nil:NilClass):
    24:                       - if thread.has_issue?
    25:                         %p= thread.issue_link
    26:                     %td.activity
    27:                       = thread.latest_activity
    28:                     %td.meta
    29:                       = time_tag_with_title(thread.latest_activity_date) do
    30:                         - t ".thread_latest_activity", time_ago: time_ago_in_words(thread.latest_activity_date)
  app/decorators/thread_list_decorator.rb:20:in `block in latest_activity'
  app/decorators/thread_list_decorator.rb:19:in `latest_activity'
  app/views/dashboards/show.html.haml:27:in `block in _app_views_dashboards_show_html_haml___525061909785760729_53887580'
  app/views/dashboards/show.html.haml:20:in `_app_views_dashboards_show_html_haml___525061909785760729_53887580'
```

**Comment by nikolai-b** [comment]
Fixed in 762dc85f6e
