### ISSUE TITLE
Location saving failing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#685]
Several reports of this - major regression.

Saving a location at `/user/locations` fails:

```
I, [2017-02-10T15:58:35.972678 #5688]  INFO -- : Started POST "/user/locations" for 82.2.125.53 at 2017-02-10 15:58:35 +0000
I, [2017-02-10T15:58:35.976680 #5688]  INFO -- : Processing by User::LocationsController#create as HTML
I, [2017-02-10T15:58:35.977253 #5688]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"v3FarDsLAXe9z3rNaHw5s2ud7mJNMXhDbM5ULxN8pkNIJuJjGow2vLbtVSMS9AOW0lKTtpi5mqFJ19tLPOljBQ==", "user_location"=>{"category_id"=>"2", "loc_json"=>"{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[0.13267278671264648,52.20628638059045],[0.13623476028442383,52.20641787737846],[0.13546228408813477,52.20478728970119],[0.13267278671264648,52.20628638059045]]]}}]}"}, "commit"=>"Save this location"}
I, [2017-02-10T15:58:35.996387 #5688]  INFO -- : Completed 500 Internal Server Error in 19ms (ActiveRecord: 4.4ms)
I, [2017-02-10T15:58:36.015897 #5688]  INFO -- : [Rollbar] Scheduling item
I, [2017-02-10T15:58:36.016042 #5688]  INFO -- : [Rollbar] Sending item
I, [2017-02-10T15:58:36.760503 #5688]  INFO -- : [Rollbar] Success
I, [2017-02-10T15:58:36.760873 #5688]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=504ea20e-1a33-4041-b99e-dcbb5ccde890 (only available if report was successful)
F, [2017-02-10T15:58:36.765434 #5688] FATAL -- : 
ActiveRecord::StatementInvalid (PG::InternalError: ERROR:  Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.
HINT:  Change argument 2: 'GEOMETRYCOLLECTION(POLYGON((0.132672786712646 52.2062863805904,0.136234760284...'
: SELECT "issues".* FROM "issues" WHERE "issues"."deleted_at" IS NULL AND (ST_Intersects(ST_CollectionExtract(location, 3), '0020000007000010e600000001000000000300000001000000043fc0fb6c00000000404a1a6797951f833fc1702400000000404a1a6be6a8533b3fc156d400000000404a1a36784bf3983fc0fb6c00000000404a1a6797951f83') OR
             ST_Intersects(ST_CollectionExtract(location, 2), '0020000007000010e600000001000000000300000001000000043fc0fb6c00000000404a1a6797951f833fc1702400000000404a1a6be6a8533b3fc156d400000000404a1a36784bf3983fc0fb6c00000000404a1a6797951f83') OR
             ST_Intersects(ST_CollectionExtract(location, 1), '0020000007000010e600000001000000000300000001000000043fc0fb6c00000000404a1a6797951f833fc1702400000000404a1a6be6a8533b3fc156d400000000404a1a36784bf3983fc0fb6c00000000404a1a6797951f83'))):
  app/models/user_location_observer.rb:5:in `after_save'
  app/controllers/user/locations_controller.rb:14:in `create'
```

Probably related to #681.

**Comment by nikolai-b** [comment]
I believe it is a dup of #676.  I'll see if I can cherry-pick the commits over.

**Comment by mvl22** [comment]
Thanks. If it works on staging, just push it into live without needing further checking from me.

**Comment by galund** [comment]
Working for me now - many thanks

**Comment by mvl22** [comment]
Thanks for sorting this out, Nikolai.
