### ISSUE TITLE
Thread creation is broken, with error 500

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#701]
A user informs me that, in each of the following two cases, their attempt to convert the following planning application resulted in a error 500, with the outcome being conversion to an issue but not creation of an associated thread:

17/0566/FUL (in Cambridge)
17/0559/FUL (in Cambridge)

I wonder if this is related to the combining of the issue & thread screen, but I would have thought this would have been encountered before now.

**Comment by mvl22** [comment]
The user adds:

"Very strange. When I go into the issue and then click discuss, it brings up the text I had written but not been able to post. When I then hit submit, I get the error screen again. So we have two issues at the moment that I can't progress."

**Comment by smsm1** [comment]
Do you have a link to the issue that has been createed?

**Comment by mvl22** [comment]
@nikolai-b Just to say that this is blocking some campaigning work so should be considered high priority against other issues please.

Here are the issues for the two applications I noted. In both cases, just try to create a thread, and submit, and the error 500 appears:

> 17/0566/FUL

https://camcycle.cyclescape.org/issues/2531

> 17/0559/FUL

https://camcycle.cyclescape.org/issues/2530

**Comment by mvl22** [comment]
I've discovered this is happening for new threads of any kind, not just those relating to planning applications.

**Comment by mvl22** [comment]
@nikolai-b Here is the stack trace:

```
I, [2017-04-19T13:22:59.288271 #30977]  INFO -- : Started POST "/issues/2531-planning-application-17-0566-ful-renewal-of-shop-front-rear-cycle-parking/threads" for 131.111.38.5 at 2017-04-19 13:22:59 +0100
I, [2017-04-19T13:22:59.293579 #30977]  INFO -- : Processing by Issue::MessageThreadsController#create as HTML
I, [2017-04-19T13:22:59.294000 #30977]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"iRk1n+673oB+4a9onoNRALJ7prLXqZsqSuq2Vlauq2Nuk78eyk87XBoKjTfGu4fbFanNeFBH90YIVG7mCaEHjw==", "thread"=>{"title"=>"Planning application : 17/0566/FUL Renewal of shop front, rear cycle parking", "group_id"=>"2", "privacy"=>"group"}, "message"=>{"body"=>"Minor application, someone might be interested. 2 sheffield stands at rear of shop. \r\n\r\n\r\n\r\nRenewal of shop front, installation of cassetted awning and new store to rear of premises.\r\n\r\n\r\n31 Burleigh Street Cambridge CB1 1DG\r\n\r\n\r\nhttps://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=summary&keyVal=ONH8D3DXIXZ00\r\n\r\nCambridge\r\n\r\nApplication reference : 17/0566/FUL\r\n"}, "commit"=>"Create Thread", "issue_id"=>"2531-planning-application-17-0566-ful-renewal-of-shop-front-rear-cycle-parking"}
I, [2017-04-19T13:23:00.394599 #30977]  INFO -- : Completed 500 Internal Server Error in 1100ms (ActiveRecord: 175.3ms)
I, [2017-04-19T13:23:00.418734 #30977]  INFO -- : [Rollbar] Scheduling item
I, [2017-04-19T13:23:00.418902 #30977]  INFO -- : [Rollbar] Sending item
I, [2017-04-19T13:23:00.859013 #30977]  INFO -- : [Rollbar] Success
I, [2017-04-19T13:23:00.859468 #30977]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=b436853e-a116-4f27-bce4-521d37d9b3fe (only available if report was successful)
F, [2017-04-19T13:23:00.864128 #30977] FATAL -- :
ActiveRecord::StatementInvalid (PG::InternalError: ERROR:  GEOSIntersects: TopologyException: side location conflict at 0.1334535949472791 52.17613240382228
: SELECT "user_locations".* FROM "user_locations" INNER JOIN "users" ON "users"."id" = "user_locations"."user_id" AND "users"."deleted_at" IS NULL INNER JOIN "user_prefs" ON "user_prefs"."user_id" = "users"."id" WHERE (ST_Intersects(ST_CollectionExtract(location, 3), '0020000003000010e600000001000000053fc124fa8b4bf8fd404a1a616b54e2b03fc10435efa615a9404a1a40a6b93ccd3fc0e37154003255404a1a616b54e2b03fc10435efa615a9404a1a822ff088933fc124fa8b4bf8fd404a1a616b54e2b0') OR
               ST_Intersects(ST_CollectionExtract(location, 2), '0020000003000010e600000001000000053fc124fa8b4bf8fd404a1a616b54e2b03fc10435efa615a9404a1a40a6b93ccd3fc0e37154003255404a1a616b54e2b03fc10435efa615a9404a1a822ff088933fc124fa8b4bf8fd404a1a616b54e2b0') OR
               ST_Intersects(ST_CollectionExtract(location, 1), '0020000003000010e600000001000000053fc124fa8b4bf8fd404a1a616b54e2b03fc10435efa615a9404a1a40a6b93ccd3fc0e37154003255404a1a616b54e2b03fc10435efa615a9404a1a822ff088933fc124fa8b4bf8fd404a1a616b54e2b0')) AND "users"."disabled_at" IS NULL AND "users"."deleted_at" IS NULL AND "user_prefs"."involve_my_locations" = 'subscribe'):
  app/workers/thread_subscriber.rb:32:in `subscribe_issue_users'
  app/workers/thread_subscriber.rb:9:in `subscribe_users'
  app/models/message_thread_observer.rb:32:in `after_save'
  app/controllers/message_threads_controller.rb:82:in `create'
  app/controllers/issue/message_threads_controller.rb:22:in `create'
```

**Comment by nikolai-b** [comment]
Should be fixed by https://github.com/cyclestreets/cyclescape/commit/16245300a3b5c618bded86f2db62a9475ce4ed20 and https://github.com/cyclestreets/cyclescape/commit/8a9460268115ea5cbae27ae5d20d9e11283ce6de should stop this type of thing creating a 500
