### ISSUE TITLE
E-mail gateway following server change

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#870]
Incoming and outgoing e-mail seems not to be working.

**Comment by nikolai-b** [comment]
Could this be mythic beasts?  I think they might have banned our server's IP.  The credentials are correct but we are getting:

```
Net::ReadTimeout

/usr/lib/ruby/2.3.0/net/protocol.rb:176:in `rbuf_fill'
/usr/lib/ruby/2.3.0/net/protocol.rb:154:in `readuntil'
/usr/lib/ruby/2.3.0/net/protocol.rb:164:in `readline'
/usr/lib/ruby/2.3.0/net/smtp.rb:955:in `recv_response'
/usr/lib/ruby/2.3.0/net/smtp.rb:556:in `block in do_start'
/usr/lib/ruby/2.3.0/net/smtp.rb:965:in `critical'
/usr/lib/ruby/2.3.0/net/smtp.rb:556:in `do_start'
/usr/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/var/www/cyclescape/shared/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
```

**Comment by mvl22** [comment]
Yep, this is an SMTP authentication issue very likely.
