### ISSUE TITLE
Poll messages break the email digest

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#957]
The use of [`@message`]( https://github.com/cyclestreets/cyclescape/blob/d84ac42af97fbf137f11a5de415562a2c4351e72/app/views/thread_mailer/_new_poll_message.text.erb#L7) doesn't work for the digest.  The [spec](https://github.com/cyclestreets/cyclescape/blob/d84ac42af97fbf137f11a5de415562a2c4351e72/spec/mailers/thread_mailer_spec.rb#L79) should be forced to include all message types.

```
Caused by:
NoMethodError: undefined method `to_key' for nil:NilClass
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/record_identifier.rb:108:in `record_key_for_dom_id'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/record_identifier.rb:90:in `dom_id'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/_new_poll_message.html.haml:6:in `_app_views_thread_mailer__new_poll_message_html_haml__2699259893680880634_47268438558320'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:159:in `block in render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:354:in `instrument_render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:157:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:312:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:49:in `render_partial'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/helpers/rendering_helper.rb:36:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/haml-5.1.2/lib/haml/helpers/action_view_mods.rb:15:in `render'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:22:in `block (3 levels) in _app_views_thread_mailer_digest_html_erb___4168895952181154133_47268446058020'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:19:in `each'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:19:in `block (2 levels) in _app_views_thread_mailer_digest_html_erb___4168895952181154133_47268446058020'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:12:in `each'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:12:in `with_index'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:12:in `block in _app_views_thread_mailer_digest_html_erb___4168895952181154133_47268446058020'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:3:in `each'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/views/thread_mailer/digest.html.erb:3:in `_app_views_thread_mailer_digest_html_erb___4168895952181154133_47268446058020'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:159:in `block in render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:354:in `instrument_render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:157:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:16:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:44:in `render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:25:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:103:in `_render_template'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:84:in `render_to_body'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/rendering.rb:25:in `render'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:943:in `block in collect_responses_from_templates'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:940:in `each'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:940:in `each'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:940:in `map'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:940:in `collect_responses_from_templates'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:925:in `collect_responses'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:828:in `mail'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/mailers/thread_mailer.rb:14:in `digest'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:25:in `block in process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:24:in `process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:607:in `block in process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:606:in `process'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:122:in `tap'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/models/user.rb:123:in `block in email_digests!'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/app/models/user.rb:117:in `email_digests!'
/var/www/cyclescape/releases/c4a19003453e0605f109fd247b1149781a8fa2c5/lib/tasks/scheduled.rake:27:in `block (2 levels) in <top (required)>'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => scheduled:email_user_digests
```

**Comment by mvl22** [comment]
Nice work.
