### ISSUE TITLE
Planning applications API call failing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#993]
scheduled:new_planning_applications --silent

is giving a stack trace:

```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Authority name can't be blank, Authority param can't be blank
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/planning_application_worker.rb:68:in `block (2 levels) in add_applications'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/planning_application_worker.rb:59:in `each'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/planning_application_worker.rb:59:in `block in add_applications'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/planning_application_worker.rb:58:in `add_applications'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/planning_application_worker.rb:15:in `process!'
/var/www/cyclescape/releases/40e05bd5dc96565ad5963e1fac9b4d019567eb7c/lib/tasks/scheduled.rake:11:in `block (2 levels) in <top (required)>'
/var/www/cyclescape/shared/bundle/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => scheduled:new_planning_applications
(See full trace by running task with --trace)
```

**Comment by mvl22** [comment]
I know the PlanIt API is under development, and perhaps the call has changed.
